### ISSUE TITLE
Problems with Cordova and Ionic with the current version 

### ISSUE THREAD

**Issue by JPfeP** [robertesler/cordova-pd#1]
Hi, 

I tried with success in the past your cordova plugin but it seems that things have evolved a little bit with the build environment. 

First, adding the plugin like the documentation says won't work anymore: 
` npm ERR! package.json Non-registry package missing package.json: git+https://github.com/robertesler/cordova-pd.git.`

The --nofetch flag is mandatory to be able to install it like the old way.

Secondly, after adding the <plugin> line in the config.xml as required, I get:
```
Discovered plugin "PdPlugin" in config.xml. Adding it to the project
Failed to restore plugin "PdPlugin" from config.xml.
You might need to try adding it again. 
Error: Error: Registry returned 404 for GET on https://registry.npmjs.org/PdPlugin
```

I don't know how to resolve this issue currently (any help appreciated).

At last, I went on the libpd Github site and it seems that they have bumped their core version to 1.0.2 and the one you provide is 1.0.1. 

Have you any intention to provide an updated version of your work to address theses issues ?

**Comment by robertesler** [comment]
Thank you for contacting me and using the plugin.  I think this is a rather simple issue of a package.json file now being required by the Cordova CLI to add plugins.  I can fix this and test in the next few days.  I don't know if I can get a new Ionic 2/AngularJS wrapper ready that quickly but will try to get the plugin updated as soon as I can.  
 For now the plugin can most likely still be installed manually if you need it before then.

**Comment by JPfeP** [comment]
Thank for your quick answer, yes indeed it seems it is just this file needed to be added. I can wait in the meanwhile. BTW, if it matters, my environment:

Ionic Framework: 3.9.2
Ionic App Scripts: 3.1.8
Angular Core: 5.0.3
Angular Compiler CLI: 5.0.3
Node: 9.2.1
OS Platform: Linux 4.13

**Comment by robertesler** [comment]
I've added the package.json generated by the plugman CLI.  It appears to download and install fine.  It successfully builds on both iOS and Android.  I could only test on MacOS and so let me know if anything goes wrong with your platform.  I'll update the readme.md file to reflect changes to the config.xml, apparently cordova automatically writes the plugin into the config.xml now.  
  I plan to update the core libpd library soon, but will need some more time to fully test any new changes or features.  For now I'm closing this issue and creating a new one for the libpd update.  Thanks again.
