### ISSUE TITLE
Update libpd core

### ISSUE THREAD

**Issue by robertesler** [robertesler/cordova-pd#2]
The libpd core to this plugin is now at least one version out of date.  Update to most recent version.

**Comment by JPfeP** [comment]
Hi, 

Are things progressing nicely ?

I am back on my project with this plugin and I am ready to test any update.  

BTW, have you discovered the problem with "Error: Error: Registry returned 404 for GET on https://registry.npmjs.org/PdPlugin" ? Cordova-pd installs fine with the new package.json but build still fails after that on the 404 error.

**Comment by robertesler** [comment]
I've updated the README.md.  I've added the plugin to the npm registry, though I don't know why this mattered, it hopefully fixes your error.  I'm unable to reproduce the error.  The install instructions have changed as well as some of the Android instructions.  It looks like Android/Cordova/Ionic have changed quite a bit so I'm still debugging the updated libpd core library.  For now you can use the version included with this plugin or manually change to the 1.0.2 version yourself.  Libpd is also not behaving well.  
But I just built an Android Ionic project (the conference template) and it worked fine.  Let me know if there are any other issues.  Thanks for using the plugin.

**Comment by robertesler** [comment]
Updated to most recent version of libpd, pd-core... Seems stable and builds on Android and iOS.  Will benchmark test on devices soon.
