### ISSUE TITLE
Pbm with sendMessage()  

### ISSUE THREAD

**Issue by JPfeP** [robertesler/cordova-pd#4]
Hi,

I can receive messages and lists in my app, but in the other direction I cannot send them to a receive object in the Pd patch.

I am not sure of the syntax either, looking in the java wrapper shows the functions expect some JSON objects:
```
 if(action.equals("sendMessage"))
        {
            this.sendMessage(args.getString(0), args.getString(1), args.getJSONObject(2));
            return true;
}
```

I tried this :
`Pd.sendMessage("Test","one",{"two":"2.3","plop":"three"});`

No error message in the debugger but no data received in Pd.  

But that would be weird to force the use of some name/value pairs since Pd doesn't have support for this natively. I tried at first with a simple Array, but no data delivered either. 

What is the proper syntax for sendMessage() ?

**Comment by robertesler** [comment]
I mention that these things are funny in the documentation.  
If you were do something like below it will get your data to libpd, but after that I don't know what happens.  I can't test anything on Android right now.
`<script>
                var list={1:"hello", 2:"snoopy" };
                </script>
            <button onclick="Javascript: window.plugins.pd.sendMessage('myMessage', 'bang', list);">Message</button>`
Cordova passes all arguments as a JSONArray. But libpd assumes your arguments to messages and lists are variable so it wants variable length args.  Javascript handles variable arguments different and cordova doesn't seem to offer an easy option.  This may just be a limitation of cordova and libpd.

Try sending symbols, bangs or numbers.  
I can try a few things in the next few weeks, but I could use help in finding a solution.

**Comment by JPfeP** [comment]
I am still scratching my head but here are a few informations:
1) I copied your example in my Ionic project associated to a button, it didn't work. Since I am still new to Typescript may be there is a specific way to declare a JSON object ? I tried different ways, even from text with JSON.parse() and verifying in the console that my JSON object was well formed. But no luck... Same behavior, no error message, nothing on the other end in Pd.

2) I could not resist to hack myself the wrapper PdPlugin.java and this following line works (!), but is not ideal:
`this.sendMessage(args.getString(0), args.getString(1), args.get(2).toString());`
The toString() function is mandatory, At first I tried "args.getString(2)" and it worked as well at the cost of course to limit the number of items passed by the function (and cast it to string).
May be they have changed how libpd deals with this ? This function seems to need pure strings which is a bit weird, but probably I found something not relevant. 

3) I read your explanations and understand part of them. Java doesn't have arrays like in JS where you can mix types so JSONArray fills the gap. But why using "getJSONObject()" then ? Wouldn't it be simpler to use getJSONArray() instead ?  Anyway, I know very little about Java so, I can say I don't see the solution and I don't know where to look to understand how the java side of libpd parse the JSONObject.

**Comment by robertesler** [comment]
To comment on your tests:
1)  Typescript is it's own beast.  There is a simple typescript implementation in the cordova-pd.js comments. My example was just pure js.  
2) Thanks for passing along that hack.  It could just become in the future the message portion of the `sendMessage(receiveName, message, list)` 
combines the arguments as a string and then tries to convert them back to their appropriate types, 
`sendMessage(receiveName, message) //no list now` 
but ultimately libpd wants an array of objects which could be any type of argument like (10, 3.14159, "bang").  Moreover, messages in Pd are also a bit finicky unless they are hard coded in a patch.

3) Since Cordova passes the arguments to a plugin's function as JSONArray, all arguments are actually objects inside that array, however, some have specific types like integers, strings and floats.  Since libpd wants an undefined number of arguments for a message or a list, you need to bundle all of the arguments (of different types) together in a JSONObject.  That is just what Cordova seems to do.  I don't know if there is a better way, but I'm limited to the Cordova framework.    

Right now I'm thinking that the solution may be to keep everything as a single long string in javascript and parse it in Java into numbers and strings since that is what Pd is looking for and then give libpd a formatted Object[].  
For performance reasons it's probably better to not use these (I may even temporarily remove them) and instead send floats, bangs and symbols and hard code your messages in the pd patch.  I'll keep investigating this issue.  (It's also a problem on iOS too).

**Comment by JPfeP** [comment]
Thanks for your answers. It's late here but I think I might have part of the solution, if not all of it. You will be able to come with a definitive fix soon I guess, as you are far better than me with Java. 

The problem is, I think, a confusion in the meaning of the term "object" in different contexts. A JSONObject is a just a bunch of name/value pairs and nothing else. See this:

https://www.w3schools.com/js/js_json_objects.asp

This is not what wants libpd. It wants an object, yep, but from another kind. That's why getJSONObject() was not working.

I made another dirty hack with this kind of object (copied/pasted loosely from some examples provided by pd-for android) and it works:
```
 if(action.equals("sendMessage"))
 {
            List<Object> liste = new ArrayList<Object>();
            liste.add("badam");
            liste.add(1.3);
            this.sendMessage(args.getString(0), args.getString(1), liste.toArray());
            return true;
} 
  
```
In my app, If I send a message, I can get all the arguments in Pd ! And, I have not verified yet, but I think the types are preserved for the ones I injected. Now the last thing to do is to copy the data we get with either "args.get(2)" or "args.getJSONArray(2) may be. But it's very late, so that would be for tomorrow. :)

BTW for this to work it's needed to import this, in PdPlugin.java:
`import java.util.ArrayList;`

**Comment by robertesler** [comment]
Try the latest push.  It works on iOS now.  Treat your arguments and lists as a single string in your javascript and it seems to work.  I haven't tested it on Android yet, but the code builds.

**Comment by JPfeP** [comment]
Ok, looking at your Plugin.java modification, interesting. 

I found on my side another solution, but I think yours has a more direct way to build the final object. We might mix the 2 solutions may be for the best code ? I know very little about java and I did this, it works and preserve the type of the items passed as an array from JS code:

```
if(action.equals("sendMessage"))
        {
            List<Object> liste = new ArrayList<Object>();
            for (int i=0; i<args.getJSONArray(2).length(); i++) {
              liste.add(args.getJSONArray(2).get(i));
            }
            this.sendMessage(args.getString(0), args.getString(1), liste.toArray());
            return true;
        }

```

Basically we need to find the best way to convert the retrieved JSONArray to the final Object.

**Comment by robertesler** [comment]
Yeah, I like your code.  My main problem is on the JS side, do I allow variable arguments or control the syntax, and the headache, by doing String parsing on the Java/Obj-C side?   So right now I'm choosing to control the syntax in the JS by making the arguments for a message, or a list, a string.  Then parse the string into numbers or strings later.  
I think packaging arguments as a JSONObject in the JS is clunky and probably involves just as many steps as string parsing.  I'm also dealing with cross-platform issues too and strings are easier to deal with in Obj-C than JSONs.  
Thanks for testing all this stuff, it's really helping make the plugin better.  I'm going to close this issue for now.  I can reopen it if any of the new code isn't working properly.
