### ISSUE TITLE
compile problem after upgrading android platform to android@11

### ISSUE THREAD

**Issue by knooiwark** [robertesler/cordova-pd#5]
Been working on a app using Cordova 11.0.0 and this amazing pure data plugin. For adding the android platform I did:

`cordova platform add android`

Everything went without issues until now... When uploading a signed AAB to the google dev play console, it doesn't accept it because the  app target api = 30 and must be 31 or higher (requirement sinds august 2022):

![image](https://user-images.githubusercontent.com/73115954/190901351-5a7f90bd-9cd4-413b-b609-291a91413f09.png)

To try to fix this, I did the following:

1. `cordova platform remove android`
2. `cordova platform add android@11`
3. added this line in the config.xml: `<preference name="android-targetSdkVersion" value="31" />`

But now the app is not compiling anymore, would you mind to have a look? Thanks!

```
E:\Projects\a>cordova run android
(node:15020) ExperimentalWarning: The fs.promises API is experimental
Checking Java JDK and Android SDK versions
ANDROID_HOME=C:\Dev\android\sdk (recommended setting)
ANDROID_SDK_ROOT=undefined (DEPRECATED)
Using Android SDK: undefined
Subproject Path: CordovaLib
Subproject Path: app

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Script 'E:\Projects\a\platforms\android\org.urbanstew.cordova.pd\a-pd.gradle' line: 8

* What went wrong:
A problem occurred evaluating script.
> Could not find method compile() for arguments [{name=pd-core-1.0.3, ext=aar}] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':app'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2s
Command failed with exit code 1: E:\Projects\a\platforms\android\gradlew cdvBuildDebug -b E:\Projects\a\platforms\android\build.gradle
```

**Comment by knooiwark** [comment]
Looks like I found a way to fix it!

1. change `compile `into `implementation` in the file projectname-pd.gradle in `platforms\android\org.urbanstew.cordova.pd`
2. copy pd-core-1.0.3.aar from `\plugins\org.urbanstew.cordova.pd\libs` to `\platforms\android\app\src\main\libs`

_compile seems to be deprecated or removed in the case of Gradle 7+_

**Comment by robertesler** [comment]
Nice find @knooiwark!  I knew about `compile` being deprecated but forgot it was still in the Gradle file.  I'll make the change and update the code sometime this week.   I just updated the plugin last week and I had another issue with the Android version but it seems entirely different than yours.  
I'm glad to hear your using the plugin.  And thanks for the feedback on your solution.  I'll close this for now but should a problem come up it can be reopened.
